[build]
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://prompt-api-worker.presenta.workers.dev/:splat"
  status = 200

# SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

